<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Practice extends Model
{
    public $timestamps = false; // Disabilita create_at e update_at non riconosciute da sqlite

    protected $fillable = [
        'codice',
        'is_in_corso',
        'titolo',
        'titolo_esteso',
        'zona',
        'strade',
        'cup',
        'finanziamento',
        'finanziamento_note',
        'rup',
        'fascicolo',
        'importo',
        'is_rl',
        'is_mims',
        'rl_codice',
        'mims_codice',
        'avvio_servizio_at',
        'is_avvio_progettazione',
        'progettista',
        'sicurezza',
        'file_count',
        'file_effettivi_count',
        'fte_at',
        'def_at',
        'ese_at',
        'is_cds',
        'cds_chiusa_at',
        'is_avvio_gara',
        'contratto_at',
        'is_lavori_in_corso',
        'direttore_lavori',
        'assistente_dl',
        'consegna_lavori_at',
        'impresa',
        'lavori_note',
        'is_cre',
        'cre_at',
        'appunti_progettazione',
        'pratica_note',
        'bdap',
        'bdap_convalidato',
        'bdap_note',
        'sito_internet',
        'sito_internet_nota',
        'determina_gruppo',
        'check_at',
        'modifica_at',
        'modifica_utente',
        'scadenza_progetto',
        'scadenza_affidamento',
        'scadenza_esecuzione',
        'gruppo',
        'coordinate',
        'file_nuovi',
    ];
}
